repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: pretty-format-json
      - id: check-json
      - id: sort-simple-yaml
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        exclude: README.md
